### ISSUE TITLE
Can you make a aimbot?

### ISSUE THREAD

**Issue by Agenlone1y2016** [Speedi13/BFV-SimpleCheat#2]
I tried it.
But it is a DLL.
I don't know how to do this.

By the way, can you tell me how to make a FairFight screenshot cleaner?
I think the FairFight screenshot cleaner is the most troublesome.
I also want to know how to find the offset. If I can do that. I can find the offset by myself. Then, I can update this! yeeess!

**Comment by Speedi13** [comment]
Hello Fink233H,

I updated the offsets
https://github.com/Speedi13/BFV-SimpleCheat/blob/master/BFV-SimpleCheat/FrostbiteSDK.h
https://github.com/Speedi13/BFV-SimpleCheat/blob/master/BFV-SimpleCheat/CustomOcclusionQueryManager.cpp

You can download the updated binary from UC
https://www.unknowncheats.me/forum/downloads.php?do=file&id=25710

You need a injector to load the DLL into the game
I use this one https://www.unknowncheats.me/forum/downloads.php?do=file&id=11063
But I also posted code on a simple injector 
https://github.com/Speedi13/DriveSizeSpoofer/blob/master/DriveSizeManager/Injector.cpp

Doing a screenshot cleaner seems to be way to difficult for you to achieve at the moment.
Maybe look at what Douggem said to beginners, he is a very well known cheat developer who did some cool unique stuff in Arma
https://www.youtube.com/watch?v=tNwta7A2kKA
For finding offsets, you need to know reverse engineering, its also used in the Anti-Malware industry a lot
https://www.youtube.com/watch?v=242Tn0IL2jE

**Comment by Agenlone1y2016** [comment]
Thanks!
How to inject I know. And I will try to find the offsets.
But how to make a aimbot? Maybe it is difficult. But I also want to know. 
In Battlefield can I move the mouse by using the Mouse event? Does it will be discovered?
And when the game update, can you make a video to demonstrate how to find the offsets ?

**Comment by Speedi13** [comment]
> And when the game update, can you make a video to demonstrate how to find the offsets ?
Just check the last page of the "Battlefield V Reversing: Struct & Offsets Thread" on UC, new offsets will be posted there

https://www.unknowncheats.me/forum/battlefield-v/288137-battlefield-reversing-struct-offsets-thread.html

> In Battlefield can I move the mouse by using the Mouse event? Does it will be discovered?

they do some SetWindowsHookEx to prevent mouse event input if you are not in a vehicle iirc
also they do some tampering checks on the view angles.
So there is no 'easy' way I can recommend.

**Comment by Agenlone1y2016** [comment]
I found a problem. The hack cannot display vehicle properly.
Just like the yellow string in the picture.
How to fix it?

By the way, are you an EA employee?
![8f3a40079ba499ed23077a366e383fb](https://user-images.githubusercontent.com/35143699/51383915-b7b87500-1b55-11e9-9fec-6d79fa84113c.jpg)

**Comment by Speedi13** [comment]
> I found a problem. The hack cannot display vehicle properly.

that is not a problem, I didn't add a box for vehicles.

> By the way, are you an EA employee?

yes ofc. Every cheat coder has to be.

**Comment by Agenlone1y2016** [comment]
>that is not a problem, I didn't add a box for vehicles.

Yes, I know that you didn't add a box for vehicles.
But can you add them next time?

And how to achieve No Recoil?
Do you want to update the BF1 Trainer?
