### ISSUE TITLE
help updating

### ISSUE THREAD

**Issue by n0c1v0z** [Speedi13/BFV-SimpleCheat#5]
how to update for personal use? :D

**Comment by Speedi13** [comment]
something with the CustomOcclusionQueryManager is crashing
Just remove it and update the offsets ;)

**Comment by ring0jke** [comment]
I just removed an CustomOcclusionQueryManager from source but its still crashing,even with newest offsets from UC :(

**Comment by Speedi13** [comment]
I updated the project now :smiley: :wink: 

Link to the commit: https://github.com/Speedi13/BFV-SimpleCheat/commit/facfda06f69f49bf20b86acf87e2145b81c5ed91
